import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [{ type: "doc", id: "index" }],
  repo_basic_skills: [{ type: "autogenerated", dirName: "basic_skills" }],
  repo_expanse_101: [{ type: "autogenerated", dirName: "expanse-101" }],
  repo_galyleo: [{ type: "autogenerated", dirName: "galyleo" }],
  repo_hpc_security: [{ type: "autogenerated", dirName: "hpc-security" }],
  repo_sdsc_summer_institute_2021: [{ type: "autogenerated", dirName: "sdsc-summer-institute-2021" }],
  repo_sdsc_summer_institute_2022: [{ type: "autogenerated", dirName: "sdsc-summer-institute-2022" }],
  repo_sdsc_summer_institute_2023: [{ type: "autogenerated", dirName: "sdsc-summer-institute-2023" }],
  repo_sdsc_summer_institute_2024: [{ type: "autogenerated", dirName: "sdsc-summer-institute-2024" }],
  repo_sdsc_summer_institute_2025: [{ type: "autogenerated", dirName: "sdsc-summer-institute-2025" }],
  repo_tscc_101: [{ type: "autogenerated", dirName: "tscc-101" }],
};

export default sidebars;
