import fs from "fs";
import path from "path";

export function repoHasDocs(repoName, outRoot) {
  const repoDir = path.join(outRoot, repoName);
  if (!fs.existsSync(repoDir)) return false;

  const stack = [repoDir];
  while (stack.length > 0) {
    const current = stack.pop();
    const entries = fs.readdirSync(current, { withFileTypes: true });
    for (const entry of entries) {
      if (entry.name.startsWith(".")) continue;
      const abs = path.join(current, entry.name);
      if (entry.isDirectory()) {
        stack.push(abs);
        continue;
      }
      if (/\.(md|mdx)$/i.test(entry.name)) return true;
    }
  }
  return false;
}

export function refreshCatalogDocAvailability(deps) {
  const {
    OUT_ROOT,
    REPO_CATALOG_PATH,
    SUBMODULES_DOCS_PATH,
    SUBMODULE_META,
    normalizeRepoUrl,
    parseGitHubOwnerRepo,
  } = deps;

  if (!fs.existsSync(REPO_CATALOG_PATH)) return;

  try {
    let manualTopicMap = {};
    let manualRepoMap = {};
    let defaultBranch = "main";
    if (fs.existsSync(SUBMODULES_DOCS_PATH)) {
      try {
        const cfg = JSON.parse(fs.readFileSync(SUBMODULES_DOCS_PATH, "utf8"));
        defaultBranch = String(cfg?.defaultBranch || "main").trim() || "main";
        const manualRepos = Array.isArray(cfg?.manualRepos) ? cfg.manualRepos : [];
        for (const r of manualRepos) {
          const name = String(r?.name || "").trim();
          if (!name) continue;
          manualRepoMap[name] = r;
          const topics = Array.from(
            new Set(
              [
                ...(Array.isArray(r?.topics) ? r.topics : []),
                ...(r?.topic ? [r.topic] : []),
              ]
                .map((t) => String(t).trim().toLowerCase())
                .filter(Boolean)
            )
          );
          if (topics.length > 0) {
            manualTopicMap[name] = topics;
          }
        }
      } catch (err) {
        console.warn(`! Could not parse manual topic overrides: ${err?.message || err}`);
      }
    }

    const raw = fs.readFileSync(REPO_CATALOG_PATH, "utf8");
    const payload = JSON.parse(raw);
    if (!Array.isArray(payload?.repos)) return;

    payload.repos = payload.repos.map((repo) => {
      const name = String(repo?.name || "").trim();
      if (!name) return repo;
      const configuredTopics = manualTopicMap[name] || [];
      return {
        ...repo,
        topics: configuredTopics.length > 0 ? configuredTopics : Array.isArray(repo?.topics) ? repo.topics : [],
        hasDocs: repoHasDocs(name, OUT_ROOT),
      };
    });

    const existingNames = new Set(
      payload.repos
        .map((r) => String(r?.name || "").trim())
        .filter(Boolean)
    );
    for (const [name, manual] of Object.entries(manualRepoMap)) {
      if (existingNames.has(name)) continue;
      const normalizedUrl = normalizeRepoUrl(String(manual?.url || ""));
      const parsed = parseGitHubOwnerRepo(normalizedUrl);
      const route = repoHasDocs(name, OUT_ROOT) ? `/${name}/` : null;
      const submodulePath = `docs_external/${name}`;
      const submoduleMeta = SUBMODULE_META.get(submodulePath);
      payload.repos.push({
        id: name,
        name,
        owner: parsed.owner,
        fullName: parsed.owner && parsed.repo ? `${parsed.owner}/${parsed.repo}` : name,
        url: normalizedUrl,
        branch: String(manual?.branch || submoduleMeta?.branch || defaultBranch || "main"),
        source: "manual",
        topics: manualTopicMap[name] || [],
        route,
        hasDocs: Boolean(route),
      });
    }

    payload.repos.sort((a, b) => String(a?.name || "").localeCompare(String(b?.name || "")));
    payload.generatedAt = new Date().toISOString();

    fs.writeFileSync(REPO_CATALOG_PATH, `${JSON.stringify(payload, null, 2)}\n`, "utf8");
  } catch (err) {
    console.warn(`! Could not refresh catalog availability: ${err?.message || err}`);
  }
}

export function generateRepoSidebars(deps) {
  const { SUBMODULE_META, SIDEBARS_PATH, toSidebarId, OUT_ROOT } = deps;

  const repoNames = Array.from(SUBMODULE_META.values())
    .filter((m) => m.path.startsWith("docs_external/"))
    .map((m) => m.path.replace(/^docs_external\//, ""))
    .filter((name) => repoHasDocs(name, OUT_ROOT))
    .sort((a, b) => a.localeCompare(b));

  const lines = [
    'import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";',
    "",
    "const sidebars: SidebarsConfig = {",
    '  tutorialSidebar: [{ type: "doc", id: "index" }],',
  ];

  for (const repoName of repoNames) {
    lines.push(
      `  ${toSidebarId(repoName)}: [{ type: "autogenerated", dirName: ${JSON.stringify(repoName)} }],`
    );
  }

  lines.push("};", "", "export default sidebars;", "");
  fs.writeFileSync(SIDEBARS_PATH, lines.join("\n"), "utf8");
}
